display_set_gui_size(960, 540)
if (obj_player.state == states.freefallland && shake_mag > 0)
    draw_sprite(spr_pepinoHUDstun, -1, 120, 80)
else if (obj_player.state == states.mach1 || obj_player.state == states.freefall || obj_player.state == states.tackle || obj_player.state == states.punch)
    draw_sprite(spr_pepinoHUDmach1, -1, 120, 80)
else if (obj_player.state == states.mach2)
    draw_sprite(spr_pepinoHUDmach2, -1, 120, 80)
else if (obj_player.state == states.hurt)
    draw_sprite(spr_pepinoHUDhurt, -1, 120, 80)
else if (obj_player.state == states.victory || obj_player.state == states.keyget)
    draw_sprite(spr_pepinoHUDhappy, -1, 120, 80)
else
	draw_sprite(spr_pepinoHUD, -1, 120, 80)
if (obj_player.state == states.mach1 && obj_player.movespeed < 4)
    draw_sprite(spr_speedbar, 1, 120, 120)
else if (obj_player.state == states.mach1 && obj_player.movespeed >= 4 && obj_player.movespeed < 6)
    draw_sprite(spr_speedbar, 2, 120, 120)
else if (obj_player.movespeed >= 6 && obj_player.movespeed < 8)
    draw_sprite(spr_speedbar, 3, 120, 120)
else if (obj_player.movespeed >= 8 && obj_player.movespeed < 10)
    draw_sprite(spr_speedbar, 4, 120, 120)
else if (obj_player.movespeed >= 10)
    draw_sprite(spr_speedbarmax, -1, 120, 120)
else
	draw_sprite(spr_speedbar, 0, 120, 120)
font = font_add_sprite(spr_numbers, 48, 0, -10)
draw_set_font(font)
draw_set_halign(fa_center)
draw_set_color(c_white)
draw_text(190, 65, string_hash_to_newline(global.collect))
if (global.key_inv == 1)
    draw_sprite(spr_key, -1, 180, 30)
draw_sprite(spr_inv, -1, 180, 30)
draw_set_blend_mode(bm_normal)

